In [1]:
import numpy as np
import pandas as pd

# Load data
data=pd.read_csv('smart_grid_stability_augmented.csv')

data.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [3]:
X=data
y=data['stabf']
# convert categorial value into numericals
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['stabf']=le.fit_transform(X['stabf'])
y=le.transform(y)

In [4]:
X.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,1
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,0
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,1
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,1
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,1

In [5]:
# Spliting data into Feature and
X=data[['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1','g2','g3','g4','stab']]
y=data['stabf']

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)  # 70% training and 30% test

In [6]:
# Import MLPClassifer 
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train,y_train)

Iteration 1, loss = 0.52737462
Iteration 2, loss = 0.25654969
Iteration 3, loss = 0.12774345
Iteration 4, loss = 0.10621567
Iteration 5, loss = 0.07408558
Iteration 6, loss = 0.06302863
Iteration 7, loss = 0.06036861
Iteration 8, loss = 0.04860867
Iteration 9, loss = 0.04222648
Iteration 10, loss = 0.04832057
Iteration 11, loss = 0.04094042
Iteration 12, loss = 0.03582655
Iteration 13, loss = 0.02901170
Iteration 14, loss = 0.03266581
Iteration 15, loss = 0.02505997
Iteration 16, loss = 0.02504154
Iteration 17, loss = 0.02955124
Iteration 18, loss = 0.02541199
Iteration 19, loss = 0.02528832
Iteration 20, loss = 0.02765856
Iteration 21, loss = 0.01928530
Iteration 22, loss = 0.02146047
Iteration 23, loss = 0.02740342
Iteration 24, loss = 0.01884853
Iteration 25, loss = 0.01599883
Iteration 26, loss = 0.03015112
Iteration 27, loss = 0.02136932
Iteration 28, loss = 0.01903403
Iteration 29, loss = 0.03667762
Iteration 30, loss = 0.01497259
Iteration 31, loss = 0.01529651
Iteration 32, loss = 0.01515193
Iteration 33, loss = 0.01277071
Iteration 34, loss = 0.01586467
Iteration 35, loss = 0.01331998
Iteration 36, loss = 0.01362248
Iteration 37, loss = 0.01790913
Iteration 38, loss = 0.01403740
Iteration 39, loss = 0.01360282
Iteration 40, loss = 0.02236825
Iteration 41, loss = 0.02720131
Iteration 42, loss = 0.01523148
Iteration 43, loss = 0.01327015
Iteration 44, loss = 0.01380299
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5, verbose=True)

In [7]:
# Make prediction on test dataset
ypred=clf.predict(X_test)

# Import accuracy score 
from sklearn.metrics import accuracy_score

# Calcuate accuracy
accuracy_score(y_test,ypred)

0.9898333333333333